# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# $Id: GNUACEWorkspaceCreator.pm 2490 2015-03-20 20:50:04Z mitza $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/sanjayvnair/Sanjay/CHREC/OpenDDS-3.9/ACE_wrappers/bin/mwc.pl -type gnuace LiveSystem.mwc
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: LiveSystem_Common LiveSystem_LiveSystem

depend: LiveSystem_Common-depend LiveSystem_LiveSystem-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_Common $(@)
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_LiveSystem $(@)

.PHONY: LiveSystem_Common
LiveSystem_Common:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_Common all

.PHONY: LiveSystem_Common-depend
LiveSystem_Common-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_Common depend

.PHONY: LiveSystem_LiveSystem
LiveSystem_LiveSystem: LiveSystem_Common
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_LiveSystem all

.PHONY: LiveSystem_LiveSystem-depend
LiveSystem_LiveSystem-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.LiveSystem_LiveSystem depend

project_name_list:
	@echo LiveSystem_Common
	@echo LiveSystem_LiveSystem
