// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p10
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_LIVESYSTEMTYPESUPPORTC_Y5VU1M_H_
#define _TAO_IDL_LIVESYSTEMTYPESUPPORTC_Y5VU1M_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "LiveSystemC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace LiveSystem
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< LiveSystem::StringMsg, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> StringMsgSeq;
  

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_StringMsgSeq;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_LIVESYSTEM_STRINGMSGTYPESUPPORT__VAR_OUT_CH_)
#define _LIVESYSTEM_STRINGMSGTYPESUPPORT__VAR_OUT_CH_

  class StringMsgTypeSupport;
  typedef StringMsgTypeSupport *StringMsgTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        StringMsgTypeSupport
      >
    StringMsgTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        StringMsgTypeSupport
      >
    StringMsgTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  StringMsgTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef StringMsgTypeSupport_ptr _ptr_type;
    typedef StringMsgTypeSupport_var _var_type;
    typedef StringMsgTypeSupport_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static StringMsgTypeSupport_ptr _duplicate (StringMsgTypeSupport_ptr obj);

    static void _tao_release (StringMsgTypeSupport_ptr obj);

    static StringMsgTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static StringMsgTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static StringMsgTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    StringMsgTypeSupport (void);

    

    virtual ~StringMsgTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    StringMsgTypeSupport (const StringMsgTypeSupport &);

    void operator= (const StringMsgTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_StringMsgTypeSupport;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_LIVESYSTEM_STRINGMSGDATAWRITER__VAR_OUT_CH_)
#define _LIVESYSTEM_STRINGMSGDATAWRITER__VAR_OUT_CH_

  class StringMsgDataWriter;
  typedef StringMsgDataWriter *StringMsgDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        StringMsgDataWriter
      >
    StringMsgDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        StringMsgDataWriter
      >
    StringMsgDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  StringMsgDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef StringMsgDataWriter_ptr _ptr_type;
    typedef StringMsgDataWriter_var _var_type;
    typedef StringMsgDataWriter_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static StringMsgDataWriter_ptr _duplicate (StringMsgDataWriter_ptr obj);

    static void _tao_release (StringMsgDataWriter_ptr obj);

    static StringMsgDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static StringMsgDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static StringMsgDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::LiveSystem::StringMsg & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::LiveSystem::StringMsg & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::LiveSystem::StringMsg & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::LiveSystem::StringMsg & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::LiveSystem::StringMsg & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::LiveSystem::StringMsg & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::LiveSystem::StringMsg & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::LiveSystem::StringMsg & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::LiveSystem::StringMsg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::LiveSystem::StringMsg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    StringMsgDataWriter (void);

    

    virtual ~StringMsgDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    StringMsgDataWriter (const StringMsgDataWriter &);

    void operator= (const StringMsgDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_StringMsgDataWriter;

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_LIVESYSTEM_STRINGMSGDATAREADER__VAR_OUT_CH_)
#define _LIVESYSTEM_STRINGMSGDATAREADER__VAR_OUT_CH_

  class StringMsgDataReader;
  typedef StringMsgDataReader *StringMsgDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        StringMsgDataReader
      >
    StringMsgDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        StringMsgDataReader
      >
    StringMsgDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  StringMsgDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef StringMsgDataReader_ptr _ptr_type;
    typedef StringMsgDataReader_var _var_type;
    typedef StringMsgDataReader_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static StringMsgDataReader_ptr _duplicate (StringMsgDataReader_ptr obj);

    static void _tao_release (StringMsgDataReader_ptr obj);

    static StringMsgDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static StringMsgDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static StringMsgDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::LiveSystem::StringMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::LiveSystem::StringMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::LiveSystem::StringMsg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::LiveSystem::StringMsg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::LiveSystem::StringMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::LiveSystem::StringMsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::LiveSystem::StringMsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::LiveSystem::StringMsg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::LiveSystem::StringMsg & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    StringMsgDataReader (void);

    

    virtual ~StringMsgDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    StringMsgDataReader (const StringMsgDataReader &);

    void operator= (const StringMsgDataReader &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_StringMsgDataReader;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module LiveSystem

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_LIVESYSTEM_STRINGMSGTYPESUPPORT__TRAITS_)
#define _LIVESYSTEM_STRINGMSGTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::LiveSystem::StringMsgTypeSupport>
  {
    static ::LiveSystem::StringMsgTypeSupport_ptr duplicate (
        ::LiveSystem::StringMsgTypeSupport_ptr p);
    static void release (
        ::LiveSystem::StringMsgTypeSupport_ptr p);
    static ::LiveSystem::StringMsgTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::LiveSystem::StringMsgTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_LIVESYSTEM_STRINGMSGDATAWRITER__TRAITS_)
#define _LIVESYSTEM_STRINGMSGDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::LiveSystem::StringMsgDataWriter>
  {
    static ::LiveSystem::StringMsgDataWriter_ptr duplicate (
        ::LiveSystem::StringMsgDataWriter_ptr p);
    static void release (
        ::LiveSystem::StringMsgDataWriter_ptr p);
    static ::LiveSystem::StringMsgDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::LiveSystem::StringMsgDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_LIVESYSTEM_STRINGMSGDATAREADER__TRAITS_)
#define _LIVESYSTEM_STRINGMSGDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::LiveSystem::StringMsgDataReader>
  {
    static ::LiveSystem::StringMsgDataReader_ptr duplicate (
        ::LiveSystem::StringMsgDataReader_ptr p);
    static void release (
        ::LiveSystem::StringMsgDataReader_ptr p);
    static ::LiveSystem::StringMsgDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::LiveSystem::StringMsgDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace LiveSystem
{
   void operator<<= ( ::CORBA::Any &, StringMsgTypeSupport_ptr); // copying
   void operator<<= ( ::CORBA::Any &, StringMsgTypeSupport_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, StringMsgTypeSupport_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgTypeSupport_ptr); // copying
 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgTypeSupport_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, LiveSystem::StringMsgTypeSupport_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace LiveSystem
{
   void operator<<= ( ::CORBA::Any &, StringMsgDataWriter_ptr); // copying
   void operator<<= ( ::CORBA::Any &, StringMsgDataWriter_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, StringMsgDataWriter_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgDataWriter_ptr); // copying
 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgDataWriter_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, LiveSystem::StringMsgDataWriter_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace LiveSystem
{
   void operator<<= ( ::CORBA::Any &, StringMsgDataReader_ptr); // copying
   void operator<<= ( ::CORBA::Any &, StringMsgDataReader_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, StringMsgDataReader_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgDataReader_ptr); // copying
 void operator<<= (::CORBA::Any &, LiveSystem::StringMsgDataReader_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, LiveSystem::StringMsgDataReader_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "LiveSystemTypeSupportC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

