/* -*- C++ -*- */
/* Generated by /home/sanjayvnair/Sanjay/CHREC/OpenDDS-3.9/bin/opendds_idl version 3.9 (ACE version 6.2a_p10) running on input file Messenger.idl */
#ifndef OPENDDS_IDL_GENERATED_MESSENGERTYPESUPPORTIMPL_H_G0HRYK
#define OPENDDS_IDL_GENERATED_MESSENGERTYPESUPPORTIMPL_H_G0HRYK
#include "MessengerC.h"
#include "dds/DCPS/Definitions.h"
#include "MessengerTypeSupportC.h"
#include "dds/DCPS/DataReaderImpl_T.h"
#include "dds/DCPS/DataWriterImpl_T.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl_T.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Messenger */



/* Begin STRUCT: Message */

namespace OpenDDS { namespace DCPS {

void gen_find_size(const Messenger::Message& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Messenger::Message& stru);

bool operator>>(Serializer& strm, Messenger::Message& stru);

bool gen_is_bounded_size(const Messenger::Message&);

size_t gen_max_marshaled_size(const Messenger::Message& stru, bool align);

bool gen_is_bounded_size(KeyOnly<const Messenger::Message>);

size_t gen_max_marshaled_size(KeyOnly<const Messenger::Message> stru, bool align);

void gen_find_size(KeyOnly<const Messenger::Message> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const Messenger::Message> stru);

bool operator>>(Serializer& strm, KeyOnly<Messenger::Message> stru);

}  }

namespace OpenDDS { namespace DCPS {

bool gen_has_key(const Messenger::Message&);

}  }

namespace Messenger {
namespace OpenDDSGenerated {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  Message_KeyLessThan {
  bool operator()(const Messenger::Message& v1, const Messenger::Message& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.subject_id < v2.subject_id) return true;
    if (v2.subject_id < v1.subject_id) return false;
    return false;
  }
};
}
}
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<Messenger::Message> {
  typedef Messenger::Message MessageType;
  typedef Messenger::MessageSeq MessageSequenceType;
  typedef Messenger::MessageTypeSupport TypeSupportType;
  typedef Messenger::MessageDataWriter DataWriterType;
  typedef Messenger::MessageDataReader DataReaderType;
  typedef Messenger::OpenDDSGenerated::Message_KeyLessThan LessThanType;

  inline static const char* type_name () { return "Messenger::Message"; }
  inline static bool gen_has_key (const MessageType& x) { return ::OpenDDS::DCPS::gen_has_key(x); }

  inline static bool gen_is_bounded_size (const MessageType& x) { return ::OpenDDS::DCPS::gen_is_bounded_size(x); }
  inline static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  inline static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  inline static bool gen_is_bounded_size (const OpenDDS::DCPS::KeyOnly<const MessageType>& x) { return ::OpenDDS::DCPS::gen_is_bounded_size(x); }
  inline static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  inline static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }

namespace Messenger {
  typedef OpenDDS::DCPS::DataWriterImpl_T<Messenger::Message> MessageDataWriterImpl;
  typedef OpenDDS::DCPS::DataReaderImpl_T<Messenger::Message> MessageDataReaderImpl;
  typedef OpenDDS::DCPS::TypeSupportImpl_T<Messenger::Message> MessageTypeSupportImpl;
}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Messenger::Message>();
void gen_skip_over(Serializer& ser, Messenger::Message*);

}  }

#endif

/* End STRUCT: Message */

/* End MODULE: Messenger */
#endif /* OPENDDS_IDL_GENERATED_MESSENGERTYPESUPPORTIMPL_H_G0HRYK */
